name: Build Check
on:

  workflow_dispatch:

  schedule:
    - cron:  '0 8 * * *'

jobs:
  check:
    name: Build Check 
    runs-on: ubuntu-latest

    outputs:
      ksu: ${{ steps.ksu.outputs.ksu_update }}
      pdx203_boot: ${{ steps.pdx203_boot.outputs.pdx203_boot_update }}
      pdx206_boot: ${{ steps.pdx203_boot.outputs.pdx206_boot_update }}

    steps:
    - uses: actions/checkout@v4
    - name: Prepare Configuration
      run: |
        echo "KERNELSU_LATEST_TAG=$(cat variables.env | grep -w "KERNELSU_LATEST_TAG" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "PDX203_SOURCE_BOOT_IMAGE=$(cat variables.env | grep -w "PDX203_SOURCE_BOOT_IMAGE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "PDX206_SOURCE_BOOT_IMAGE=$(cat variables.env | grep -w "PDX206_SOURCE_BOOT_IMAGE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install curl jq 

    - name: Check KernelSU
      id: ksu
      run: |
        tag=$(curl 'https://api.github.com/repos/tiann/KernelSU/tags' | jq -r '.[0].name')
        if [ "$tag" != "${{ env.KERNELSU_LATEST_TAG }}" ]; then
          echo "ksu_update=true" >> $GITHUB_ENV
          echo "ksu_update=true" >> $GITHUB_OUTPUT
          echo "KERNELSU_LATEST_TAG=$tag" >> $GITHUB_ENV
        fi

    - name: Check PDX203
      id: pdx203_boot
      run: |
        pdx203_boot=$(curl 'https://download.lineageos.org/api/v2/devices/pdx203/builds' | jq -r '.[0].files[] | select(.filename == "boot.img") | .url')
        if [ "$pdx203_boot" != "${{ env.PDX203_SOURCE_BOOT_IMAGE }}" ]; then
          echo "pdx203_boot_update=true" >> $GITHUB_ENV
          echo "pdx203_boot_update=true" >> $GITHUB_OUTPUT
          echo "PDX203_SOURCE_BOOT_IMAGE=$pdx203_boot" >> $GITHUB_ENV
        fi

    - name: Check PDX206
      id: pdx206_boot
      run: |
        pdx206_boot=$(curl 'https://download.lineageos.org/api/v2/devices/pdx206/builds' | jq -r '.[0].files[] | select(.filename == "boot.img") | .url')
        if [ "$pdx206_boot" != "${{ env.PDX206_SOURCE_BOOT_IMAGE }}" ]; then
          echo "pdx206_boot_update=true" >> $GITHUB_ENV
          echo "pdx206_boot_update=true" >> $GITHUB_OUTPUT
          echo "PDX206_SOURCE_BOOT_IMAGE=$pdx206_boot" >> $GITHUB_ENV
        fi

    - name: Commit variables
      if: env.ksu_update == 'true' || env.pdx203_boot_update == 'true' || env.pdx206_boot_update == 'true'
      run: |
        echo "KERNELSU_LATEST_TAG=${{ env.KERNELSU_LATEST_TAG }}" > variables.env
        echo "PDX203_SOURCE_BOOT_IMAGE=${{ env.PDX203_SOURCE_BOOT_IMAGE }}" >> variables.env
        echo "PDX206_SOURCE_BOOT_IMAGE=${{ env.PDX206_SOURCE_BOOT_IMAGE }}" >> variables.env
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add variables.env
        git diff-index --cached --quiet HEAD -- || (git commit -m "variables" && git push)

  build_kernel_pdx203:
    name: Build PDX203
    needs: check
    if: ${{ needs.check.outputs.ksu }} == 'true' || ${{ needs.check.outputs.pdx203_boot }} == 'true'
    uses: ./.github/workflows/build-kernel_pdx203.yml

  build_kernel_pdx206:
    name: Build PDX206
    needs: check
    if: ${{ needs.check.outputs.ksu }} == 'true' || ${{ needs.check.outputs.pdx206_boot }} == 'true'
    uses: ./.github/workflows/build-kernel_pdx206.yml