name: Build Check
on:

  workflow_dispatch:

  schedule:
    - cron:  '0 8 * * *'

jobs:
  check:
    name: Build Check 
    runs-on: ubuntu-latest

    steps:
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install curl jq 

    - name: Check KernelSU
      run: |
        tag=$(curl 'https://api.github.com/repos/tiann/KernelSU/tags' | jq -r '.[0].name')
        if [ "$tag" != "${{ vars.KERNELSU_LATEST_TAG }}" ]; then
          echo "ksu_update=true" >> $GITHUB_ENV
          gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/lzghzr/KernelSU_Action_Sony_sm8250/actions/variables/KERNELSU_LATEST_TAG \
          -f name='KERNELSU_LATEST_TAG' \
          -f value='$tag' 
        fi

    - name: Check PDX203
      run: |
        pdx203_boot=$(curl 'https://download.lineageos.org/api/v2/devices/pdx203/builds' | jq -r '.[0].files.[1].url')
        if [ "$pdx203_boot" != "${{ vars.PDX203_SOURCE_BOOT_IMAGE }}" ]; then
          echo "pdx203_boot_update=true" >> $GITHUB_ENV
          gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/lzghzr/KernelSU_Action_Sony_sm8250/actions/variables/PDX203_SOURCE_BOOT_IMAGE \
          -f name='PDX203_SOURCE_BOOT_IMAGE' \
          -f value='$pdx203_boot' 
        fi

    - name: Check PDX206
      run: |
        pdx206_boot=$(curl 'https://download.lineageos.org/api/v2/devices/pdx206/builds' | jq -r '.[0].files.[1].url')
        if [ "$pdx206_boot" != "${{ vars.PDX206_SOURCE_BOOT_IMAGE }}" ]; then
          echo "pdx206_boot_update=true" >> $GITHUB_ENV
          gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/lzghzr/KernelSU_Action_Sony_sm8250/actions/variables/PDX206_SOURCE_BOOT_IMAGE \
          -f name='PDX206_SOURCE_BOOT_IMAGE' \
          -f value='$pdx206_boot' 
        fi

    - name: Build PDX203
      if: env.ksu_update == 'true' || env.pdx203_boot_update == 'true'
      uses: ./build-kernel_pdx203.yml

    - name: Build PDX206
      if: env.ksu_update == 'true' || env.pdx206_boot_update == 'true'
      uses: ./build-kernel_pdx206.yml
